---
- include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Ensure Icinga 2 is started and enabled on boot
  service:
    name: icinga2
    state: "{{ icinga2_service_state }}"
    enabled: "{{ icinga2_service_enabled }}"
