---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-icinga2

  pre_tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - gnupg
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false
    - name: Install Debian Backports repository
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian' and ansible_distribution_release == 'stretch'
      changed_when: false

  post_tasks:
    - name: Ensure Icinga 2 is installed
      stat:
        path: /usr/sbin/icinga2
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg
