---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: transitiv.icinga2

  pre_tasks:
    - name: Install required packages on Debian
      apt:
        name:
          - apt-transport-https
          - gnupg
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install Backports repository on Debian Stretch
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
        state: present
        update_cache: yes
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_release == 'stretch'

  post_tasks:
    - name: Ensure Icinga 2 is installed
      stat:
        path: /usr/sbin/icinga2
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg
