---
- name: Converge
  hosts: all
  pre_tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - gnupg
        update_cache: true
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: ansible-role-icinga2
