---
- hosts: all
  tasks:
    - name: Install required packages on Debian
      apt:
        name:
          # required to add key to apt keyring
          - gnupg
          # required to verify icinga2 is running
          - procps
        update_cache: true
      when: ansible_os_family == 'Debian'

    - name: Install Backports repository on Debian Stretch
      apt_repository:
        repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main
        state: present
        update_cache: yes
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_release == 'stretch'

    - name: Install apt-transport-https on older Debian/Ubuntu versions
      apt:
        name:
          - apt-transport-https
      when:
        - ansible_os_family == 'Debian'
        - ansible_distribution_release in ['jessie', 'stretch', 'xenial']
